name: CI/CD Pipeline
on: 
  push:
    branches:
      - main
      - notes

jobs:
  react-deploy:
    name: 部署React到GitHub Pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist

  notes-deploy:
    name: 部署笔记到独立分支
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: main-repo

      - run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout --orphan notes
          git reset --hard
          git clean -fd

      - run: |
          cp -r main-repo/src/notes/* .
          git add .
          git commit -m "Update notes @ $(date +'%Y-%m-%d %H:%M:%S')"

      - uses: ad-m/github-push-action@master
        with:
          branch: notes
          force: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: fjogeleit/http-request-action@v1
        with:
          url: "http://117.72.70.19:80/webhook"
          method: POST
          contentType: "application/json"
          data: '{"ref":"${{ github.ref }}","repository":{"full_name":"${{ github.repository }}"}}'
          secret: ${{ secrets.SERVER_DEPLOY_TOKEN }}