name: CI/CD Pipeline
on: 
  push:
    branches:
      - main  # 触发React部署的分支
      - notes  # 触发笔记部署的分支

jobs:
  react-deploy:
    name: 部署React到GitHub Pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # 仅在main分支触发
    steps:
      - uses: actions/checkout@v4
      - name: 安装Node依赖
        run: npm install
      - name: 项目打包
        run: npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist

  notes-deploy:
    name: 部署笔记到独立分支
    runs-on: ubuntu-latest
    needs: react-deploy  # 依赖React部署任务（可选）
    steps:
      - uses: actions/checkout@v4
      
      - name: 创建notes分支
        run: |
          git checkout --orphan notes
          git rm -rf .
          
      - name: 同步笔记内容
        run: |
          cp -r src/notes/* .
          git add .
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Update notes @ $(date +'%Y-%m-%d %H:%M:%S')"
          
      - name: 强制推送分支
        uses: ad-m/github-push-action@master
        with:
          branch: notes
          force: true
          tokens: ${{ secrets.GITHUB_TOKEN }}

      - name: 触发服务器部署
        uses: fjogeleit/http-request-action@v1.10
        with:
          url: "http://117.72.70.19:80/webhook"
          method: "POST"
          contentType: "application/json"
          data: |
            {
              "ref": "${{ github.ref }}",
              "repository": {
                "full_name": "${{ github.repository }}"
              }
            }
          secret: "${{ secrets.SERVER_DEPLOY_TOKEN }}"  # 需在仓库Secrets中设置